/**
 * pages/TeacherDashboard.jsx
 * Teacher's class overview.
 * Loads AI data for all demo students and shows them in a table.
 * Click "View →" to see the full recommendation detail for any student.
 */

import { useState, useEffect } from "react";
import { useNavigate }         from "react-router-dom";
import { useAuth }             from "../context/AuthContext";
import { getRecommendations }  from "../services/api";
import StudentRow              from "../components/teacher/StudentRow";
import LoadingSpinner          from "../components/shared/LoadingSpinner";
import "./TeacherDashboard.css";

// All student IDs in the demo dataset
const STUDENT_IDS = [1, 2, 3, 5, 6, 7, 8, 9, 10];

export default function TeacherDashboard() {
  const { user }          = useAuth();
  const navigate          = useNavigate();
  const [students, setStudents] = useState([]);
  const [loading, setLoading]   = useState(true);
  const [error, setError]       = useState(null);
  const [filter, setFilter]     = useState("all"); // "all" | "0" | "1" | ...

  useEffect(() => {
    async function loadAll() {
      setLoading(true);
      setError(null);
      try {
        const results = await Promise.all(
          STUDENT_IDS.map((id) => getRecommendations(id, 3).catch(() => null))
        );
        setStudents(results.filter(Boolean));
      } catch (e) {
        setError(e.message);
      } finally {
        setLoading(false);
      }
    }
    loadAll();
  }, []);

  if (loading) return <LoadingSpinner text="Loading class data…" />;

  if (error) return (
    <div className="teacher-error">
      <p>Could not load class data: <strong>{error}</strong></p>
      <p>Make sure the backend is running: <code>cd backend &amp;&amp; python app.py</code></p>
    </div>
  );

  // Summary stats
  const clusters     = [...new Set(students.map((s) => s.cluster))].sort();
  const needHelp     = students.filter((s) => (s.student_features?.avg_quiz_score ?? 0) < -0.5);
  const aboveAvg     = students.filter((s) => (s.student_features?.avg_quiz_score ?? 0) >= 0.5);

  const filtered = filter === "all"
    ? students
    : students.filter((s) => String(s.cluster) === filter);

  return (
    <div className="teacher-page">

      {/* Header */}
      <div className="teacher-header">
        <div>
          <h1>Class overview</h1>
          <p className="teacher-subtitle">
            Hello, {user?.name}. Here is the AI-generated summary for your class.
          </p>
        </div>
      </div>

      {/* Summary cards */}
      <div className="teacher-summary">
        <div className="summary-card">
          <span className="summary-num">{students.length}</span>
          <span className="summary-label">Total students</span>
        </div>
        <div className="summary-card">
          <span className="summary-num">{clusters.length}</span>
          <span className="summary-label">Learning groups</span>
        </div>
        <div className="summary-card warn">
          <span className="summary-num">{needHelp.length}</span>
          <span className="summary-label">Need attention</span>
        </div>
        <div className="summary-card good">
          <span className="summary-num">{aboveAvg.length}</span>
          <span className="summary-label">Above average</span>
        </div>
      </div>

      {/* Filter */}
      <div className="teacher-filter">
        <button
          className={`filter-btn ${filter === "all" ? "active" : ""}`}
          onClick={() => setFilter("all")}
        >
          All students
        </button>
        {clusters.map((c) => (
          <button
            key={c}
            className={`filter-btn ${filter === String(c) ? "active" : ""}`}
            onClick={() => setFilter(String(c))}
          >
            Group {c + 1}
          </button>
        ))}
      </div>

      {/* Table */}
      <div className="teacher-table-wrap">
        <table className="teacher-table">
          <thead>
            <tr>
              <th>Student</th>
              <th>Group</th>
              <th>Performance</th>
              <th>Recommended topics</th>
              <th>Weak topics</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {filtered.map((s) => (
              <StudentRow
                key={s.student_id}
                student={s}
                onView={(id) => navigate(`/students/${id}`)}
              />
            ))}
          </tbody>
        </table>
      </div>

      <p className="teacher-note">
        Recommendations and groups are generated by the AI engine.
        Click "View →" to see the full SHAP explanation for any student.
      </p>
    </div>
  );
}
